# File              : configure.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 10.09.2020
# Last Modified Date: 04.10.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: creating necessary directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    mode: 0644
  loop: "{{ necessary_dirs }}"

- name: ensuring certificates directory exists
  become: true
  file:
    path: "{{ remote_certs_dir }}"
    state: directory
  when: remote_certs_path

- name: installing certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ remote_certs_path }}"
  loop:
    - "{{ local_ca_cert_file }}"
    - "{{ local_server_certs_path }}"
    - "{{ local_peer_certs_path }}"
  when: remote_certs_path

- name: setting up etcd_3 client as default
  become: true
  lineinfile:
    path: "/etc/environment"
    line: "ETCDCTL_API=3"
  when: set_v3

- name: installing etcd.service
  become: true
  template:
    src: "{{ service_file }}"
    dest: "/etc/systemd/system/etcd.service"
    owner: root
    mode: 0644
  notify:
    - enable etcd
  when: service_file
