# File              : configure.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 10.09.2020
# Last Modified Date: 24.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: ensuring data directory exists
  become: true
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: root
    mode: 0644

- name: ensuring wal directory exists
  become: true
  file:
    path: "{{ wal_dir }}"
    state: directory
    owner: root
    mode: 0644

- name: ensuring certificates directory exists
  become: true
  file:
    path: "{{ remote_certs_location }}"
    state: directory

- name: installing certificates
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ remote_certs_location }}"
  loop:
    - "{{ local_ca_cert_file }}"
    - "{{ local_client_keys_path }}"
    - "{{ local_server_keys_path }}"
    - "{{ local_peer_keys_path }}"

- name: installing etcd.service
  become: true
  template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/etcd.service"
    owner: root
    mode: 0644
  notify:
    - enable etcd
