# File              : install.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 10.09.2020
# Last Modified Date: 24.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: updating before installation
  become: true
  apt:
    update_cache: true
    cache_valid_time: 0
    force_apt_get: true
    upgrade: dist

- name: removing apt package if installed
  become: true
  apt:
    name: etcd
    state: absent
    autoremove: true
    autoclean: true

- name: downloading
  become: true
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ version }}/etcd-v{{ version }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd.tar.gz"
    owner: root
    mode: 0444

- name: unpacking
  become: true
  unarchive:
    src: "/tmp/etcd.tar.gz"
    dest: "/tmp"
    mode: 0755
    owner: root
    remote_src: true

- name: installing
  become: true
  copy:
    src: "/tmp/etcd-v{{ version }}-linux-amd64/{{ item }}"
    dest: "/usr/bin"
    mode: 0755
    owner: root
    remote_src: true
  loop:
    - etcd
    - etcdctl 
