# File              : uninstall.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 15.09.2020
# Last Modified Date: 24.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: stopping etcd daemon
  become: true
  service:
    name: etcd
    state: stopped
    enabled: false

- name: uninstalling
  become: true
  file:
    path: "/usr/bin/{{ item }}"
    state: absent
  loop:
    - etcd
    - etcdctl

- name: removing data
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/var/lib/etcd"
    - "/etc/etcd"
    - "/etc/systemd/system/etcd.service"
  when: state == 'full_uninstall'

- name: cleaning after uninstalling
  become: true
  apt:
    autoremove: true
    autoclean: true
