# File              : uninstall.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 15.09.2020
# Last Modified Date: 03.10.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: stopping etcd daemon
  become: true
  service:
    name: etcd
    state: stopped
    enabled: false

- name: uninstalling
  become: true
  file:
    path: "/usr/bin/{{ item }}"
    state: absent
  loop:
    - etcd
    - etcdctl

- name: removing created directories
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ necessary_dirs }}"
  when: state == 'full_uninstall'

- name: removing certificates directory
  become: true
  file:
    path: "{{ remote_certs_dir }}"
    state: absent
  when: state == 'full_uninstall'

- name: removing service
  become: true
  file:
    path: "/etc/systemd/system/etcd.service"
    state: absent
  when: service_file

- name: removing etcd_3 env var
  become: true
  lineinfile:
    path: "/etc/environment"
    line: "export ETCDCTL_API=3"
    state: absent
  when: set_v3
